### ISSUE TITLE
Total cvap is not exactly the sum of each race

### ISSUE THREAD

**Issue by kuriwaki** [christopherkenny/cvap#2]
This graph compares the total CVAP with the sum of the cvap_race partitions:

```
block_est <- cvap_distribute_censable('DE')

block_est %>% 
    mutate(cvap_implied_total = cvap_white + cvap_black + cvap_hisp + cvap_asian + 
               cvap_aian + cvap_nhpi + cvap_two + cvap_other) %>% 
    ggplot(aes(cvap, cvap_implied_total))  + 
    geom_abline(alpha = 0.5, color = "red") + 
    geom_point(size = 0.1, alpha = 0.25) +
    coord_equal() + theme_bw()
```

<img width="308" alt="image" src="https://user-images.githubusercontent.com/8290417/179602338-d444e1ee-5196-4cda-82af-bb6362c66dc9.png">

So the implied total of races is not exactly the same as the `cvap` variable, though they are highly correlated. I guess this makes sense in that each cvap variable is separately estimated and so some noise gets included independently in each one. Might be worth a documentation note somewhere. 

This particular discrepancy can be relevant in EI applications, when the row margins must add up exactly to the grand total.

**Comment by christopherkenny** [comment]
Thanks Shiro. This is an interesting point. They should always align at the block group level, but the block level is necessarily estimated and it uses the subgroup that matches for that purpose. I can add a note. 

Maybe, it's worth adding a method that does it all by the same piece so that counts should be consistent. Would that be helpful?

**Comment by kuriwaki** [comment]
A version that is consistent with respect totals would be nice for EI, especially if that carries through to the VTD level. But it's not a strict necessity for me at the moment. For now we can ignore the total cvap variable and used the implied total for the total cvap population. Thanks!

**Comment by christopherkenny** [comment]
Sorry @kuriwaki, I let this get lost. 

I've added an option `include_implied` which adds a column `impl_cvap` for the implied `cvap`. This allows you to retain both the "best" total and the "implied" total. Default for `include_implied` is `TRUE`, as it adds about 10ms to the runtime on average!
